name: Dive the Maldives
favicon: null
layout_spectrum: 0.9417671158444136
typography_spectrum: 0.9552225959487259
title: Dive the Maldives
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9145757530350238
  lightness: 0.13159049022942781
  saturation: 0.5530947521328926
  rhythmicContrast: 0.5648707847576588
purpose: []
